services:
  tinychat:
    container_name: tinychat
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIRECRAWL_API_KEY=
      - FIRECRAWL_API_URL=
      - LITELLM_URL=
      - QUICKCHART_URL=
      - TERRARIUM_URL=
    read_only: true
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
