services:
  tinychat:
    container_name: tinychat
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIRECRAWL_API_KEY=
      - FIRECRAWL_API_URL=http://192.168.10.120:3002
    volumes:
      - ./models.yaml:/app/models.yaml
    read_only: true
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
